#!/bin/bash
# =============================================================================
# MODULE: marzban.sh - Marzban Panel Installation and Configuration
# Version: 2.0.0
# =============================================================================
# Features:
# - SQLite and MariaDB database support
# - Docker Compose configuration
# - Admin user creation via CLI/API
# - Environment configuration
# - Container management
# =============================================================================

# Source core module if not already loaded
if [[ -z "${CORE_LOADED:-}" ]]; then
    source "$(dirname "${BASH_SOURCE[0]}")/core.sh"
fi

# -----------------------------------------------------------------------------
# CONSTANTS
# -----------------------------------------------------------------------------
readonly MARZBAN_IMAGE="gozargah/marzban:latest"
readonly MARIADB_IMAGE="mariadb:10.11"
readonly MARZBAN_DIR="${MARZBAN_DIR:-/opt/marzban}"
readonly MARZBAN_DATA_DIR="/var/lib/marzban"
readonly MARZBAN_LOGS_DIR="${MARZBAN_DATA_DIR}/logs"

# -----------------------------------------------------------------------------
# DIRECTORY SETUP
# -----------------------------------------------------------------------------

# Create all required directories
create_marzban_directories() {
    log_info "Creating Marzban directories..."
    
    local directories=(
        "$MARZBAN_DIR"
        "$MARZBAN_DATA_DIR"
        "$MARZBAN_LOGS_DIR"
        "${MARZBAN_DATA_DIR}/certs"
        "${MARZBAN_DATA_DIR}/xray-core"
    )
    
    for dir in "${directories[@]}"; do
        create_dir "$dir" "0755"
    done
    
    # Set proper permissions for data directory
    chmod 0750 "$MARZBAN_DATA_DIR"
    
    log_success "Directories created"
}

# -----------------------------------------------------------------------------
# ENVIRONMENT CONFIGURATION
# -----------------------------------------------------------------------------

# Generate Marzban environment file
generate_marzban_env() {
    local database_type="${1:-sqlite}"
    local panel_domain="${2:-}"
    local dashboard_port="${3:-8000}"
    local dashboard_path="${4:-/dashboard/}"
    
    log_step "Generating Marzban Environment Configuration"
    
    local env_file="${MARZBAN_DIR}/.env"
    
    # Generate secure secrets
    local secret_key
    local jwt_secret
    
    secret_key=$(generate_password 32)
    jwt_secret=$(generate_password 32)
    
    # Database URL based on type
    local database_url
    
    case "$database_type" in
        sqlite)
            database_url="sqlite:////var/lib/marzban/db.sqlite3"
            ;;
        mariadb|mysql)
            local db_password="${MARIADB_PASSWORD:-$(generate_password 24)}"
            database_url="mysql+pymysql://marzban:${db_password}@marzban-db:3306/marzban"
            export MARIADB_PASSWORD="$db_password"
            ;;
        *)
            log_error "Unknown database type: ${database_type}"
            return 1
            ;;
    esac
    
    # Subscription URL prefix
    local sub_url_prefix=""
    if [[ -n "$panel_domain" ]]; then
        sub_url_prefix="https://${panel_domain}"
    fi
    
    cat > "$env_file" << EOF
# =============================================================================
# Marzban Configuration
# Generated by Marzban Installer on $(date '+%Y-%m-%d %H:%M:%S')
# =============================================================================

# --- Application Settings ---
UVICORN_HOST=0.0.0.0
UVICORN_PORT=${dashboard_port}
DEBUG=false
DOCS=false

# --- Security ---
SECRET_KEY=${secret_key}
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440

# --- Database ---
SQLALCHEMY_DATABASE_URL=${database_url}

# --- Dashboard ---
DASHBOARD_PATH=${dashboard_path}

# --- Subscription ---
XRAY_SUBSCRIPTION_URL_PREFIX=${sub_url_prefix}

# --- Xray ---
XRAY_JSON=/var/lib/marzban/xray_config.json
XRAY_EXECUTABLE_PATH=/var/lib/marzban/xray-core/xray
XRAY_ASSETS_PATH=/var/lib/marzban/xray-core

# --- Telegram Bot (optional) ---
# TELEGRAM_API_TOKEN=
# TELEGRAM_ADMIN_ID=
# TELEGRAM_PROXY_URL=

# --- Webhook (optional) ---
# WEBHOOK_ADDRESS=
# WEBHOOK_SECRET=

# --- Custom Templates ---
# CUSTOM_TEMPLATES_DIRECTORY=/var/lib/marzban/templates/

# --- Logging ---
VITE_BASE_API=/api/
EOF

    chmod 0600 "$env_file"
    register_file "$env_file"
    
    log_success "Environment configuration saved to: ${env_file}"
    
    # Export for later use
    export MARZBAN_ENV_FILE="$env_file"
    export MARZBAN_SECRET_KEY="$secret_key"
}

# -----------------------------------------------------------------------------
# DOCKER COMPOSE GENERATION
# -----------------------------------------------------------------------------

# Generate Docker Compose file with optional MariaDB
generate_docker_compose() {
    local database_type="${1:-sqlite}"
    local dashboard_port="${2:-8000}"
    local network_mode="${3:-host}"
    
    log_step "Generating Docker Compose Configuration"
    
    local compose_file="${MARZBAN_DIR}/docker-compose.yml"
    
    # Start compose file
    cat > "$compose_file" << EOF
version: "3.8"

# =============================================================================
# Marzban Docker Compose Configuration
# Generated by Marzban Installer on $(date '+%Y-%m-%d %H:%M:%S')
# Database: ${database_type}
# =============================================================================

services:
  marzban:
    image: ${MARZBAN_IMAGE}
    container_name: marzban
    restart: unless-stopped
EOF

    # Network mode
    if [[ "$network_mode" == "host" ]]; then
        cat >> "$compose_file" << EOF
    network_mode: host
EOF
    else
        cat >> "$compose_file" << EOF
    networks:
      - marzban-network
    ports:
      - "${dashboard_port}:${dashboard_port}"
EOF
    fi
    
    # Environment and volumes
    cat >> "$compose_file" << EOF
    env_file:
      - .env
    volumes:
      - ${MARZBAN_DATA_DIR}:/var/lib/marzban
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${dashboard_port}/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
EOF

    # Add MariaDB dependency if needed
    if [[ "$database_type" == "mariadb" || "$database_type" == "mysql" ]]; then
        cat >> "$compose_file" << EOF
    depends_on:
      marzban-db:
        condition: service_healthy

  marzban-db:
    image: ${MARIADB_IMAGE}
    container_name: marzban-db
    restart: unless-stopped
EOF

        if [[ "$network_mode" != "host" ]]; then
            cat >> "$compose_file" << EOF
    networks:
      - marzban-network
EOF
        else
            cat >> "$compose_file" << EOF
    network_mode: host
EOF
        fi
        
        cat >> "$compose_file" << EOF
    environment:
      MYSQL_ROOT_PASSWORD: \${MARIADB_ROOT_PASSWORD:-$(generate_password 24)}
      MYSQL_DATABASE: marzban
      MYSQL_USER: marzban
      MYSQL_PASSWORD: \${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
EOF
    fi
    
    # Networks and volumes sections
    if [[ "$network_mode" != "host" ]]; then
        cat >> "$compose_file" << EOF

networks:
  marzban-network:
    driver: bridge
EOF
    fi
    
    if [[ "$database_type" == "mariadb" || "$database_type" == "mysql" ]]; then
        cat >> "$compose_file" << EOF

volumes:
  mariadb_data:
    driver: local
EOF
    fi
    
    chmod 0644 "$compose_file"
    register_file "$compose_file"
    
    log_success "Docker Compose configuration saved"
}

# -----------------------------------------------------------------------------
# CONTAINER MANAGEMENT
# -----------------------------------------------------------------------------

# Pull Marzban Docker images
pull_marzban_images() {
    log_step "Pulling Docker Images"
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" || return 1
    
    # Pull all images defined in compose
    if ! docker compose pull; then
        log_error "Failed to pull Docker images"
        cd "$old_pwd"
        return 1
    fi
    
    cd "$old_pwd"
    log_success "Docker images pulled"
}

# Start Marzban containers
start_marzban() {
    log_step "Starting Marzban"
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" || return 1
    
    # Start containers
    if ! docker compose up -d; then
        log_error "Failed to start Marzban"
        cd "$old_pwd"
        return 1
    fi
    
    cd "$old_pwd"
    
    register_rollback "Stop Marzban" "cd '${MARZBAN_DIR}' && docker compose down"
    
    log_success "Marzban containers started"
}

# Wait for Marzban to be ready
wait_for_marzban() {
    local dashboard_port="${1:-8000}"
    local timeout="${2:-120}"
    
    log_info "Waiting for Marzban to be ready..."
    
    local elapsed=0
    local interval=3
    
    while [[ $elapsed -lt $timeout ]]; do
        # Check if container is running
        if ! docker ps --format '{{.Names}}' | grep -q '^marzban$'; then
            log_debug "Marzban container not running yet..."
            sleep "$interval"
            elapsed=$((elapsed + interval))
            continue
        fi
        
        # Check container health
        local health
        health=$(docker inspect --format='{{.State.Health.Status}}' marzban 2>/dev/null || echo "unknown")
        
        if [[ "$health" == "healthy" ]]; then
            log_success "Marzban is healthy and ready"
            return 0
        fi
        
        # Check if API is responding
        if curl -sf "http://127.0.0.1:${dashboard_port}/api/" -o /dev/null 2>/dev/null; then
            log_success "Marzban API is responding"
            return 0
        fi
        
        log_debug "Waiting... (${elapsed}/${timeout}s, health: ${health})"
        sleep "$interval"
        elapsed=$((elapsed + interval))
    done
    
    log_error "Marzban did not become ready within ${timeout} seconds"
    
    # Show container logs for debugging
    log_info "Container logs:"
    docker logs marzban --tail=30 2>&1 | head -50
    
    return 1
}

# Stop Marzban containers
stop_marzban() {
    log_info "Stopping Marzban..."
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" 2>/dev/null || return 0
    
    docker compose down 2>/dev/null || true
    
    cd "$old_pwd"
    log_success "Marzban stopped"
}

# Restart Marzban
restart_marzban() {
    log_info "Restarting Marzban..."
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" || return 1
    
    docker compose restart
    
    cd "$old_pwd"
    
    # Wait for ready
    sleep 5
    
    if docker ps --format '{{.Names}}' | grep -q '^marzban$'; then
        log_success "Marzban restarted"
        return 0
    else
        log_error "Marzban failed to restart"
        return 1
    fi
}

# -----------------------------------------------------------------------------
# ADMIN USER MANAGEMENT
# -----------------------------------------------------------------------------

# Create admin user via CLI
create_admin_user_cli() {
    local username="$1"
    local password="$2"
    
    log_step "Creating Admin User"
    
    # Wait for Marzban to be ready
    sleep 5
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" || return 1
    
    # Try to create admin user
    log_info "Creating admin user: ${username}"
    
    if docker compose exec -T marzban marzban cli admin create \
        --username "$username" \
        --password "$password" 2>/dev/null; then
        log_success "Admin user created"
        cd "$old_pwd"
        return 0
    fi
    
    # Admin might already exist, try to update
    log_info "User may exist, attempting to update password..."
    
    if docker compose exec -T marzban marzban cli admin update \
        --username "$username" \
        --password "$password" 2>/dev/null; then
        log_success "Admin password updated"
        cd "$old_pwd"
        return 0
    fi
    
    cd "$old_pwd"
    log_warn "Could not create/update admin user via CLI"
    return 1
}

# Create admin user via API (alternative method)
create_admin_user_api() {
    local username="$1"
    local password="$2"
    local dashboard_port="${3:-8000}"
    
    log_info "Creating admin user via API..."
    
    # First, check if any admin exists
    local response
    response=$(curl -sf "http://127.0.0.1:${dashboard_port}/api/admin/token" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data "username=${username}&password=${password}" 2>/dev/null)
    
    if [[ -n "$response" ]] && echo "$response" | jq -e '.access_token' &>/dev/null; then
        log_success "Admin user already exists and credentials are valid"
        return 0
    fi
    
    # If Marzban is fresh, we need to use CLI
    log_info "Using CLI to create initial admin..."
    create_admin_user_cli "$username" "$password"
}

# Save admin credentials to file
save_admin_credentials() {
    local username="$1"
    local password="$2"
    local panel_domain="${3:-localhost}"
    local dashboard_path="${4:-/dashboard/}"
    
    local creds_file="${MARZBAN_DIR}/admin_credentials.txt"
    
    cat > "$creds_file" << EOF
# Marzban Admin Credentials
# Generated: $(date '+%Y-%m-%d %H:%M:%S')
# ============================================
# KEEP THIS FILE SECURE!
# ============================================

Dashboard URL: https://${panel_domain}${dashboard_path}
Username: ${username}
Password: ${password}

# API Endpoints:
# - Token: POST https://${panel_domain}/api/admin/token
# - Users: GET https://${panel_domain}/api/users
# - Inbounds: GET https://${panel_domain}/api/inbounds
EOF

    chmod 0600 "$creds_file"
    register_file "$creds_file"
    
    log_info "Credentials saved to: ${creds_file}"
}

# -----------------------------------------------------------------------------
# XRAY CONFIGURATION
# -----------------------------------------------------------------------------

# Copy Xray core to data directory
setup_xray_for_marzban() {
    local xray_source="${1:-/var/lib/marzban/xray-core}"
    local xray_dest="${MARZBAN_DATA_DIR}/xray-core"
    
    log_info "Setting up Xray for Marzban..."
    
    create_dir "$xray_dest" "0755"
    
    # Copy Xray binary if exists
    if [[ -x "${xray_source}/xray" ]]; then
        cp "${xray_source}/xray" "${xray_dest}/xray"
        chmod +x "${xray_dest}/xray"
    fi
    
    # Copy geo files if exist
    for file in geoip.dat geosite.dat; do
        if [[ -f "${xray_source}/${file}" ]]; then
            cp "${xray_source}/${file}" "${xray_dest}/${file}"
        fi
    done
    
    log_success "Xray files copied"
}

# Copy Xray configuration
copy_xray_config() {
    local config_source="$1"
    local config_dest="${MARZBAN_DATA_DIR}/xray_config.json"
    
    if [[ -f "$config_source" ]]; then
        cp "$config_source" "$config_dest"
        chmod 0644 "$config_dest"
        register_file "$config_dest"
        log_success "Xray configuration copied"
    else
        log_warn "Xray configuration source not found: ${config_source}"
    fi
}

# -----------------------------------------------------------------------------
# STATUS AND INFORMATION
# -----------------------------------------------------------------------------

# Show Marzban status
show_marzban_status() {
    log_step "Marzban Status"
    
    echo ""
    echo "Installation Directory: ${MARZBAN_DIR}"
    echo "Data Directory: ${MARZBAN_DATA_DIR}"
    echo ""
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" 2>/dev/null || {
        echo "Marzban not installed"
        return 1
    }
    
    echo "Container Status:"
    docker compose ps
    
    echo ""
    echo "Resource Usage:"
    docker stats marzban --no-stream 2>/dev/null || echo "Container not running"
    
    cd "$old_pwd"
}

# Show Marzban logs
show_marzban_logs() {
    local lines="${1:-50}"
    local follow="${2:-false}"
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" 2>/dev/null || return 1
    
    if [[ "$follow" == "true" ]]; then
        docker compose logs -f --tail="$lines"
    else
        docker compose logs --tail="$lines"
    fi
    
    cd "$old_pwd"
}

# Update Marzban
update_marzban() {
    log_step "Updating Marzban"
    
    local old_pwd
    old_pwd=$(pwd)
    cd "$MARZBAN_DIR" || return 1
    
    # Pull latest images
    docker compose pull
    
    # Restart with new images
    docker compose up -d
    
    cd "$old_pwd"
    
    # Wait for ready
    wait_for_marzban
    
    log_success "Marzban updated"
}

# Backup Marzban
backup_marzban() {
    local backup_dir="${1:-/var/backups/marzban}"
    
    log_step "Backing up Marzban"
    
    local timestamp
    timestamp=$(date '+%Y%m%d_%H%M%S')
    local backup_name="marzban_backup_${timestamp}"
    local backup_path="${backup_dir}/${backup_name}"
    
    create_dir "$backup_dir" "0755"
    mkdir -p "$backup_path"
    
    # Stop Marzban for consistent backup
    log_info "Stopping Marzban for backup..."
    stop_marzban
    
    # Backup data directory
    if [[ -d "$MARZBAN_DATA_DIR" ]]; then
        cp -r "$MARZBAN_DATA_DIR" "${backup_path}/data"
    fi
    
    # Backup config
    if [[ -f "${MARZBAN_DIR}/.env" ]]; then
        cp "${MARZBAN_DIR}/.env" "${backup_path}/.env"
    fi
    
    if [[ -f "${MARZBAN_DIR}/docker-compose.yml" ]]; then
        cp "${MARZBAN_DIR}/docker-compose.yml" "${backup_path}/docker-compose.yml"
    fi
    
    # Create tarball
    tar -czf "${backup_path}.tar.gz" -C "$backup_dir" "$backup_name"
    rm -rf "$backup_path"
    
    # Restart Marzban
    log_info "Restarting Marzban..."
    start_marzban
    
    log_success "Backup created: ${backup_path}.tar.gz"
}

# -----------------------------------------------------------------------------
# MAIN SETUP FUNCTION
# -----------------------------------------------------------------------------

# Complete Marzban setup
setup_marzban() {
    local database_type="${1:-sqlite}"
    local panel_domain="${2:-}"
    local admin_username="${3:-admin}"
    local admin_password="${4:-}"
    local dashboard_port="${5:-8000}"
    local dashboard_path="${6:-/dashboard/}"
    local xray_config_file="${7:-}"
    
    log_step "Setting up Marzban Panel"
    
    # Generate password if not provided
    if [[ -z "$admin_password" ]]; then
        admin_password=$(generate_password 16)
        log_info "Generated admin password"
    fi
    
    # Create directories
    create_marzban_directories
    
    # Generate environment file
    generate_marzban_env "$database_type" "$panel_domain" "$dashboard_port" "$dashboard_path"
    
    # Generate Docker Compose
    generate_docker_compose "$database_type" "$dashboard_port" "host"
    
    # Setup Xray
    if [[ -n "$xray_config_file" && -f "$xray_config_file" ]]; then
        copy_xray_config "$xray_config_file"
    fi
    
    # Pull images
    pull_marzban_images
    
    # Start Marzban
    start_marzban
    
    # Wait for ready
    if ! wait_for_marzban "$dashboard_port" 180; then
        log_error "Marzban failed to start"
        return 1
    fi
    
    # Create admin user
    create_admin_user_cli "$admin_username" "$admin_password"
    
    # Save credentials
    save_admin_credentials "$admin_username" "$admin_password" "$panel_domain" "$dashboard_path"
    
    # Print summary
    echo ""
    print_separator
    echo -e "${GREEN}Marzban Setup Complete${NC}"
    print_separator
    echo ""
    echo "Dashboard URL: https://${panel_domain}${dashboard_path}"
    echo "Admin Username: ${admin_username}"
    echo "Admin Password: ${admin_password}"
    echo "Database Type: ${database_type}"
    echo ""
    print_separator
    
    # Export credentials
    export MARZBAN_ADMIN_USER="$admin_username"
    export MARZBAN_ADMIN_PASS="$admin_password"
    export MARZBAN_PANEL_URL="http://127.0.0.1:${dashboard_port}"
    
    log_success "Marzban setup completed"
}

# Export function marker
MARZBAN_MODULE_LOADED=true
