#!/bin/bash
# =============================================================================
# Module: marzban.sh
# Description: Marzban installation, database setup, admin user creation
# =============================================================================

set -euo pipefail

# Source core module if not already loaded
if [[ -z "${SCRIPT_DIR:-}" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    source "${SCRIPT_DIR}/modules/core.sh"
fi

# =============================================================================
# MARZBAN CONFIGURATION
# =============================================================================
readonly MARZBAN_REPO="https://github.com/Gozargah/Marzban"
readonly MARZBAN_IMAGE="gozargah/marzban:latest"

# =============================================================================
# CREATE MARZBAN DIRECTORIES
# =============================================================================
create_marzban_directories() {
    log_info "Creating Marzban directories..."
    
    local dirs=(
        "${MARZBAN_DIR}"
        "${MARZBAN_DATA_DIR}"
        "${MARZBAN_DATA_DIR}/certs"
        "${MARZBAN_DATA_DIR}/logs"
    )
    
    for dir in "${dirs[@]}"; do
        mkdir -p "${dir}"
    done
    
    chmod 750 "${MARZBAN_DATA_DIR}"
    
    register_rollback "rm -rf ${MARZBAN_DIR} ${MARZBAN_DATA_DIR}"
    
    log_success "Marzban directories created"
}

# =============================================================================
# GENERATE MARZBAN ENV FILE
# =============================================================================
generate_marzban_env() {
    log_step "Generating Marzban Environment Configuration"
    
    local env_file="${MARZBAN_DIR}/.env"
    local dashboard_port="${MARZBAN_DASHBOARD_PORT:-8001}"
    local api_port="${MARZBAN_API_PORT:-8001}"
    
    # Generate secrets
    local secret_key
    secret_key=$(generate_password 32)
    
    local jwt_secret
    jwt_secret=$(generate_password 32)
    
    cat > "${env_file}" << EOF
# =============================================================================
# Marzban Configuration
# Generated by Marzban Installer on $(date)
# =============================================================================

# --- Application Settings ---
UVICORN_HOST=0.0.0.0
UVICORN_PORT=${dashboard_port}
DEBUG=false
DOCS=false

# --- Security ---
SECRET_KEY=${secret_key}
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=1440

# --- Database ---
# SQLite (default)
SQLALCHEMY_DATABASE_URL=sqlite:////var/lib/marzban/db.sqlite3

# MariaDB (uncomment to use)
# SQLALCHEMY_DATABASE_URL=mysql+pymysql://marzban:${MARIADB_PASSWORD:-password}@db/marzban

# --- Xray ---
XRAY_JSON=/var/lib/marzban/xray_config.json
XRAY_EXECUTABLE_PATH=/usr/local/bin/xray
XRAY_ASSETS_PATH=/usr/local/share/xray

# --- Dashboard ---
DASHBOARD_PATH=/dashboard
SUBSCRIPTION_URL_PREFIX=

# --- Telegram Bot (optional) ---
# TELEGRAM_API_TOKEN=your_bot_token
# TELEGRAM_ADMIN_ID=your_telegram_id
# TELEGRAM_PROXY_URL=

# --- Logging ---
VITE_BASE_API=/api/
EOF

    chmod 600 "${env_file}"
    
    register_rollback "rm -f ${env_file}"
    
    log_success "Marzban environment file created"
}

# =============================================================================
# GENERATE DOCKER COMPOSE FILE
# =============================================================================
generate_docker_compose() {
    log_step "Generating Docker Compose Configuration"
    
    local compose_file="${MARZBAN_DIR}/docker-compose.yml"
    local dashboard_port="${MARZBAN_DASHBOARD_PORT:-8001}"
    local xray_port="${XRAY_PORT:-8443}"
    
    # Check if template exists
    if [[ -f "${TEMPLATES_DIR}/docker-compose.yml.tpl" ]]; then
        export MARZBAN_DASHBOARD_PORT="${dashboard_port}"
        export XRAY_PORT="${xray_port}"
        process_template "${TEMPLATES_DIR}/docker-compose.yml.tpl" "${compose_file}"
    else
        # Generate inline
        cat > "${compose_file}" << EOF
version: "3.8"

services:
  marzban:
    image: ${MARZBAN_IMAGE}
    container_name: marzban
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${MARZBAN_DATA_DIR}:/var/lib/marzban
      - ${MARZBAN_DIR}/xray_config.json:/var/lib/marzban/xray_config.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${dashboard_port}/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

# Optional: MariaDB service (uncomment to use)
#   db:
#     image: mariadb:10.11
#     container_name: marzban-db
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: \${MARIADB_ROOT_PASSWORD:-rootpassword}
#       MYSQL_DATABASE: marzban
#       MYSQL_USER: marzban
#       MYSQL_PASSWORD: \${MARIADB_PASSWORD:-password}
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

# volumes:
#   mariadb_data:
EOF
    fi
    
    register_rollback "rm -f ${compose_file}"
    
    log_success "Docker Compose file created"
}

# =============================================================================
# COPY XRAY CONFIG TO MARZBAN DIRECTORY
# =============================================================================
setup_xray_config() {
    log_info "Setting up Xray config for Marzban..."
    
    local src_config="${MARZBAN_DIR}/xray_config.json"
    local dest_config="${MARZBAN_DATA_DIR}/xray_config.json"
    
    if [[ -f "${src_config}" ]]; then
        cp "${src_config}" "${dest_config}"
        chmod 644 "${dest_config}"
        log_success "Xray config copied to data directory"
    else
        log_warn "Xray config not found, Marzban will use default"
    fi
}

# =============================================================================
# PULL MARZBAN IMAGE
# =============================================================================
pull_marzban_image() {
    log_step "Pulling Marzban Docker Image"
    
    pull_docker_image "${MARZBAN_IMAGE}"
    
    # Also pull Xray image for tools
    pull_docker_image "ghcr.io/xtls/xray-core:latest"
    
    log_success "Docker images pulled"
}

# =============================================================================
# START MARZBAN
# =============================================================================
start_marzban() {
    log_step "Starting Marzban"
    
    cd "${MARZBAN_DIR}"
    
    # Start with docker compose
    docker compose up -d
    
    # Wait for container to be healthy
    log_info "Waiting for Marzban to be ready..."
    
    local max_attempts=60
    local attempt=1
    local dashboard_port="${MARZBAN_DASHBOARD_PORT:-8001}"
    
    while [[ ${attempt} -le ${max_attempts} ]]; do
        # Check if container is running
        if docker ps | grep -q marzban; then
            # Check if API is responding
            if curl -sf "http://127.0.0.1:${dashboard_port}/api/" &>/dev/null; then
                log_success "Marzban is running and healthy"
                return 0
            fi
        fi
        
        printf "\r  Waiting... (%d/%d)" "${attempt}" "${max_attempts}"
        sleep 2
        ((attempt++))
    done
    
    printf "\r"
    log_error "Marzban failed to start within timeout"
    
    # Show logs for debugging
    log_info "Container logs:"
    docker compose logs --tail=50
    
    return 1
}

# =============================================================================
# CREATE ADMIN USER
# =============================================================================
create_admin_user() {
    log_step "Creating Admin User"
    
    local admin_user="${MARZBAN_ADMIN_USER:-admin}"
    local admin_pass="${MARZBAN_ADMIN_PASS:-}"
    
    # Generate password if not provided
    if [[ -z "${admin_pass}" ]]; then
        admin_pass=$(generate_password 16)
        log_warn "Generated admin password: ${admin_pass}"
    fi
    
    cd "${MARZBAN_DIR}"
    
    # Wait a bit for Marzban to fully initialize
    sleep 5
    
    # Create admin using Marzban CLI
    log_info "Creating admin user via CLI..."
    
    if docker compose exec -T marzban marzban cli admin create \
        --username "${admin_user}" \
        --password "${admin_pass}" 2>/dev/null; then
        log_success "Admin user created"
    else
        # Admin might already exist
        log_info "Trying to update admin password..."
        docker compose exec -T marzban marzban cli admin update \
            --username "${admin_user}" \
            --password "${admin_pass}" 2>/dev/null || true
    fi
    
    # Save credentials to a secure file
    local creds_file="${MARZBAN_DIR}/admin_credentials.txt"
    cat > "${creds_file}" << EOF
# Marzban Admin Credentials
# Generated: $(date)
# KEEP THIS FILE SECURE!

Username: ${admin_user}
Password: ${admin_pass}

Dashboard URL: https://${PANEL_DOMAIN:-localhost}/dashboard
EOF
    chmod 600 "${creds_file}"
    
    export MARZBAN_ADMIN_USER="${admin_user}"
    export MARZBAN_ADMIN_PASS="${admin_pass}"
    
    log_success "Admin credentials saved to: ${creds_file}"
}

# =============================================================================
# STOP MARZBAN
# =============================================================================
stop_marzban() {
    log_info "Stopping Marzban..."
    
    cd "${MARZBAN_DIR}" 2>/dev/null || return 0
    
    docker compose down 2>/dev/null || true
    
    log_success "Marzban stopped"
}

# =============================================================================
# RESTART MARZBAN
# =============================================================================
restart_marzban() {
    log_info "Restarting Marzban..."
    
    cd "${MARZBAN_DIR}"
    
    docker compose restart
    
    # Wait for healthy status
    sleep 5
    
    if docker ps | grep -q marzban; then
        log_success "Marzban restarted"
    else
        log_error "Marzban failed to restart"
        return 1
    fi
}

# =============================================================================
# SHOW MARZBAN STATUS
# =============================================================================
show_marzban_status() {
    log_step "Marzban Status"
    
    cd "${MARZBAN_DIR}" 2>/dev/null || {
        log_error "Marzban directory not found"
        return 1
    }
    
    echo ""
    echo "Container Status:"
    docker compose ps
    
    echo ""
    echo "Resource Usage:"
    docker stats marzban --no-stream 2>/dev/null || true
    
    echo ""
    echo "Recent Logs:"
    docker compose logs --tail=20
}

# =============================================================================
# SHOW MARZBAN LOGS
# =============================================================================
show_marzban_logs() {
    local lines="${1:-50}"
    
    cd "${MARZBAN_DIR}" 2>/dev/null || {
        log_error "Marzban directory not found"
        return 1
    }
    
    docker compose logs --tail="${lines}" -f
}

# =============================================================================
# BACKUP MARZBAN
# =============================================================================
backup_marzban() {
    log_step "Backing up Marzban"
    
    local backup_name="marzban_backup_$(date +%Y%m%d_%H%M%S)"
    local backup_path="${BACKUP_DIR}/${backup_name}"
    
    mkdir -p "${backup_path}"
    
    # Backup data directory
    if [[ -d "${MARZBAN_DATA_DIR}" ]]; then
        cp -r "${MARZBAN_DATA_DIR}" "${backup_path}/data"
    fi
    
    # Backup config
    if [[ -d "${MARZBAN_DIR}" ]]; then
        cp "${MARZBAN_DIR}/.env" "${backup_path}/.env" 2>/dev/null || true
        cp "${MARZBAN_DIR}/docker-compose.yml" "${backup_path}/docker-compose.yml" 2>/dev/null || true
        cp "${MARZBAN_DIR}/xray_config.json" "${backup_path}/xray_config.json" 2>/dev/null || true
    fi
    
    # Create tarball
    tar -czf "${backup_path}.tar.gz" -C "${BACKUP_DIR}" "${backup_name}"
    rm -rf "${backup_path}"
    
    log_success "Backup created: ${backup_path}.tar.gz"
}

# =============================================================================
# UPDATE MARZBAN
# =============================================================================
update_marzban() {
    log_step "Updating Marzban"
    
    cd "${MARZBAN_DIR}"
    
    # Backup first
    backup_marzban
    
    # Pull latest image
    docker compose pull
    
    # Restart with new image
    docker compose up -d
    
    # Wait for healthy
    sleep 10
    
    if docker ps | grep -q marzban; then
        log_success "Marzban updated successfully"
    else
        log_error "Update failed, check logs"
        return 1
    fi
}

# =============================================================================
# MAIN MARZBAN SETUP
# =============================================================================
setup_marzban() {
    log_step "=== MARZBAN SETUP ==="
    
    # Create directories
    create_marzban_directories
    
    # Generate environment file
    generate_marzban_env
    
    # Generate docker compose file
    generate_docker_compose
    
    # Setup Xray config
    setup_xray_config
    
    # Pull Docker image
    pull_marzban_image
    
    # Start Marzban
    start_marzban
    
    # Create admin user
    create_admin_user
    
    log_success "Marzban setup completed"
}

# =============================================================================
# EXPORT FUNCTIONS
# =============================================================================
export -f create_marzban_directories
export -f generate_marzban_env
export -f generate_docker_compose
export -f setup_xray_config
export -f pull_marzban_image
export -f start_marzban
export -f create_admin_user
export -f stop_marzban
export -f restart_marzban
export -f show_marzban_status
export -f show_marzban_logs
export -f backup_marzban
export -f update_marzban
export -f setup_marzban
