#!/bin/bash
#===============================================================================
#
#          FILE: install.sh
#
#         USAGE: ./install.sh [OPTIONS]
#
#   DESCRIPTION: Marzban Ultimate VPN Installer v2.0
#                Production-grade, modular, idempotent installer for
#                multi-profile VLESS/Reality VPN server powered by Marzban.
#                Engineered for hostile network environments.
#
#        AUTHOR: Generated by Claude (Anthropic) & Fixed by Gemini
#       VERSION: 2.0.1
#       CREATED: 2024
#
#===============================================================================

set -euo pipefail

#-------------------------------------------------------------------------------
# Script Constants
#-------------------------------------------------------------------------------
readonly SCRIPT_VERSION="2.0.1"
readonly SCRIPT_NAME="Marzban Ultimate VPN Installer"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly MODULES_DIR="${SCRIPT_DIR}/modules"
readonly TEMPLATES_DIR="${SCRIPT_DIR}/templates"
readonly TOOLS_DIR="${SCRIPT_DIR}/tools"
readonly DATA_DIR="${SCRIPT_DIR}/data"
readonly KEYS_DIR="${DATA_DIR}/keys"
readonly BACKUPS_DIR="${DATA_DIR}/backups"
readonly CONFIG_FILE="${DATA_DIR}/config.env"
readonly STATE_FILE="${DATA_DIR}/.install_state"
readonly LOG_FILE="${DATA_DIR}/install.log"
readonly CREDENTIALS_FILE="${DATA_DIR}/credentials.env"

# Installation destinations
readonly MARZBAN_DIR="/opt/marzban"
readonly MARZBAN_DATA_DIR="/var/lib/marzban"

#-------------------------------------------------------------------------------
# Module Loading
#-------------------------------------------------------------------------------
load_modules() {
    local modules=(
        "core.sh"
        "system.sh"
        "firewall.sh"
        "docker.sh"
        "nginx.sh"
        "database.sh"
        "certbot.sh"
        "xray.sh"
        "warp.sh"
        "marzban.sh"
        "marzban_api.sh"
        "adguard.sh"
        "cdn.sh"
    )
    
    for module in "${modules[@]}"; do
        local module_path="${MODULES_DIR}/${module}"
        if [[ -f "${module_path}" ]]; then
            # shellcheck source=/dev/null
            source "${module_path}"
        else
            echo "ERROR: Required module not found: ${module_path}" >&2
            exit 1
        fi
    done
}

#-------------------------------------------------------------------------------
# Installation State Management
#-------------------------------------------------------------------------------
save_state() {
    local phase="$1"
    local step="${2:-}"
    
    mkdir -p "$(dirname "${STATE_FILE}")"
    cat > "${STATE_FILE}" << EOF
PHASE=${phase}
STEP=${step}
TIMESTAMP=$(date -Iseconds)
VERSION=${SCRIPT_VERSION}
EOF
}

load_state() {
    if [[ -f "${STATE_FILE}" ]]; then
        # shellcheck source=/dev/null
        source "${STATE_FILE}"
        return 0
    fi
    return 1
}

clear_state() {
    rm -f "${STATE_FILE}"
}

#-------------------------------------------------------------------------------
# Interactive Configuration Wizard
#-------------------------------------------------------------------------------
run_wizard() {
    clear
    show_banner
    
    echo ""
    log_info "Starting configuration wizard..."
    echo ""
    
    # Check for resume
    if [[ -f "${STATE_FILE}" ]]; then
        load_state
        if ask_yes_no "Previous installation detected (Phase: ${PHASE:-unknown}). Resume?" "y"; then
            log_info "Resuming from phase: ${PHASE}"
            return 0
        else
            clear_state
            log_info "Starting fresh installation"
        fi
    fi
    
    #---------------------------------------------------------------------------
    # Step 1: Deployment Mode
    #---------------------------------------------------------------------------
    echo ""
    log_step "1/8" "Deployment Mode"
    echo ""
    echo "Available deployment modes:"
    echo "  1) Exit Node   - Full exit node (direct to internet)"
    echo "  2) Relay       - Relay only (forwards to another server)"  
    echo "  3) Exit+Relay  - Both modes combined"
    echo ""
    
    local mode_choice
    # FIXED: Passed descriptive strings instead of indices
    mode_choice=$(select_option "Select deployment mode" "Exit Node" "Relay Only" "Exit + Relay")
    
    # FIXED: select_option returns 0-based index (0, 1, 2...)
    case "${mode_choice}" in
        0) DEPLOYMENT_MODE="exit" ;;
        1) DEPLOYMENT_MODE="relay" ;;
        2) DEPLOYMENT_MODE="exit+relay" ;;
        *) DEPLOYMENT_MODE="exit" ;; # Fallback to avoid unbound variable
    esac
    
    log_info "Deployment mode: ${DEPLOYMENT_MODE}"
    
    #---------------------------------------------------------------------------
    # Step 2: Domain Configuration
    #---------------------------------------------------------------------------
    echo ""
    log_step "2/8" "Domain Configuration"
    echo ""
    
    PANEL_DOMAIN=$(ask_input "Enter domain for Marzban panel (e.g., panel.example.com)" "")
    if [[ -z "${PANEL_DOMAIN}" ]]; then
        log_error "Panel domain is required"
        exit 1
    fi
    
    if ask_yes_no "Do you want to enable CDN-fronted profile (whitelist bypass)?" "n"; then
        PROFILE_WHITELIST_ENABLED="true"
        CDN_DOMAIN=$(ask_input "Enter domain for CDN profile (e.g., cdn.example.com)" "")
        if [[ -z "${CDN_DOMAIN}" ]]; then
            log_error "CDN domain is required for whitelist bypass profile"
            exit 1
        fi
        
        echo ""
        echo "Available CDN providers:"
        echo "  1) GCore      - GCore CDN (recommended)"
        echo "  2) EdgeCenter - EdgeCenter CDN"
        echo ""
        
        local cdn_choice
        # FIXED: Descriptive options and 0-based index
        cdn_choice=$(select_option "Select CDN provider" "GCore" "EdgeCenter")
        
        case "${cdn_choice}" in
            0) CDN_PROVIDER="gcore" ;;
            1) CDN_PROVIDER="edgecenter" ;;
            *) CDN_PROVIDER="gcore" ;; # Fallback
        esac
    else
        PROFILE_WHITELIST_ENABLED="false"
        CDN_DOMAIN=""
        CDN_PROVIDER=""
    fi
    
    #---------------------------------------------------------------------------
    # Step 3: VPN Profiles
    #---------------------------------------------------------------------------
    echo ""
    log_step "3/8" "VPN Profiles Configuration"
    echo ""
    
    # Standard profile (always enabled)
    PROFILE_STANDARD_ENABLED="true"
    log_info "Standard profile (VLESS+Reality): ENABLED (default)"
    
    # WARP profile
    if ask_yes_no "Enable WARP profile (for geo-restricted services)?" "y"; then
        PROFILE_WARP_ENABLED="true"
        log_info "WARP profile: ENABLED"
    else
        PROFILE_WARP_ENABLED="false"
        log_info "WARP profile: DISABLED"
    fi
    
    if [[ "${PROFILE_WHITELIST_ENABLED}" == "true" ]]; then
        log_info "Whitelist bypass profile: ENABLED"
    fi
    
    #---------------------------------------------------------------------------
    # Step 4: Reality Configuration
    #---------------------------------------------------------------------------
    echo ""
    log_step "4/8" "Reality Configuration"
    echo ""
    
    REALITY_DEST=$(ask_input "Reality destination domain (camouflage)" "www.microsoft.com")
    REALITY_PORT=$(ask_input "Reality port" "443")
    
    #---------------------------------------------------------------------------
    # Step 5: Database Selection
    #---------------------------------------------------------------------------
    echo ""
    log_step "5/8" "Database Configuration"
    echo ""
    
    echo "Available database options:"
    echo "  1) SQLite  - Simple, file-based (recommended for <100 users)"
    echo "  2) MariaDB - Full database server (recommended for >100 users)"
    echo ""
    
    local db_choice
    # FIXED: Descriptive options and 0-based index
    db_choice=$(select_option "Select database type" "SQLite" "MariaDB")
    
    case "${db_choice}" in
        0) DATABASE_TYPE="sqlite" ;;
        1) 
            DATABASE_TYPE="mariadb"
            MARIADB_ROOT_PASSWORD=$(generate_password 24)
            MARIADB_PASSWORD=$(generate_password 24)
            ;;
        *) DATABASE_TYPE="sqlite" ;; # Fallback
    esac
    
    log_info "Database type: ${DATABASE_TYPE}"
    
    #---------------------------------------------------------------------------
    # Step 6: Admin Credentials
    #---------------------------------------------------------------------------
    echo ""
    log_step "6/8" "Admin Credentials"
    echo ""
    
    ADMIN_USERNAME=$(ask_input "Admin username" "admin")
    ADMIN_PASSWORD=$(ask_password "Admin password (leave empty for auto-generate)")
    
    if [[ -z "${ADMIN_PASSWORD}" ]]; then
        ADMIN_PASSWORD=$(generate_password 16)
        log_info "Generated admin password (will be shown at the end)"
    fi
    
    ADMIN_EMAIL=$(ask_input "Admin email (for SSL certificates)" "")
    
    #---------------------------------------------------------------------------
    # Step 7: Optional Components
    #---------------------------------------------------------------------------
    echo ""
    log_step "7/8" "Optional Components"
    echo ""
    
    if ask_yes_no "Install AdGuard Home (DNS-level ad blocking)?" "y"; then
        ADGUARD_ENABLED="true"
    else
        ADGUARD_ENABLED="false"
    fi
    
    if ask_yes_no "Install Fail2Ban (brute-force protection)?" "y"; then
        FAIL2BAN_ENABLED="true"
    else
        FAIL2BAN_ENABLED="false"
    fi
    
    #---------------------------------------------------------------------------
    # Step 8: System Optimization
    #---------------------------------------------------------------------------
    echo ""
    log_step "8/8" "System Optimization"
    echo ""
    
    if ask_yes_no "Install XanMod kernel with BBRv3 (requires reboot)?" "n"; then
        INSTALL_XANMOD="true"
        log_warn "System will reboot after kernel installation. Installation will resume automatically."
    else
        INSTALL_XANMOD="false"
    fi
    
    #---------------------------------------------------------------------------
    # Save Configuration
    #---------------------------------------------------------------------------
    echo ""
    log_info "Saving configuration..."
    
    mkdir -p "${DATA_DIR}"
    
    cat > "${CONFIG_FILE}" << EOF
# Marzban Ultimate VPN Installer Configuration
# Generated: $(date -Iseconds)
# Version: ${SCRIPT_VERSION}

# Deployment
DEPLOYMENT_MODE="${DEPLOYMENT_MODE}"

# Domains
PANEL_DOMAIN="${PANEL_DOMAIN}"
CDN_DOMAIN="${CDN_DOMAIN:-}"
CDN_PROVIDER="${CDN_PROVIDER:-}"

# Profiles
PROFILE_STANDARD_ENABLED="${PROFILE_STANDARD_ENABLED}"
PROFILE_WARP_ENABLED="${PROFILE_WARP_ENABLED}"
PROFILE_WHITELIST_ENABLED="${PROFILE_WHITELIST_ENABLED}"

# Reality Configuration
REALITY_DEST="${REALITY_DEST}"
REALITY_PORT="${REALITY_PORT}"

# WebSocket Configuration (for CDN profile)
WS_PORT="8444"
WS_PATH="/$(generate_random_string 12)"

# Database
DATABASE_TYPE="${DATABASE_TYPE}"
MARIADB_ROOT_PASSWORD="${MARIADB_ROOT_PASSWORD:-}"
MARIADB_PASSWORD="${MARIADB_PASSWORD:-}"

# Admin
ADMIN_USERNAME="${ADMIN_USERNAME}"
ADMIN_PASSWORD="${ADMIN_PASSWORD}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"

# Optional Components
ADGUARD_ENABLED="${ADGUARD_ENABLED}"
FAIL2BAN_ENABLED="${FAIL2BAN_ENABLED}"

# System
INSTALL_XANMOD="${INSTALL_XANMOD}"

# SSL
SSL_MANAGED_BY_CDN="false"
EOF

    chmod 600 "${CONFIG_FILE}"
    
    log_success "Configuration saved to ${CONFIG_FILE}"
    
    #---------------------------------------------------------------------------
    # Confirmation
    #---------------------------------------------------------------------------
    echo ""
    echo "=============================================="
    echo "         INSTALLATION SUMMARY"
    echo "=============================================="
    echo ""
    echo "Deployment Mode:    ${DEPLOYMENT_MODE}"
    echo "Panel Domain:       ${PANEL_DOMAIN}"
    [[ -n "${CDN_DOMAIN:-}" ]] && echo "CDN Domain:         ${CDN_DOMAIN}"
    echo ""
    echo "Profiles:"
    echo "  - Standard:       ${PROFILE_STANDARD_ENABLED}"
    echo "  - WARP:           ${PROFILE_WARP_ENABLED}"
    echo "  - Whitelist:      ${PROFILE_WHITELIST_ENABLED}"
    echo ""
    echo "Database:           ${DATABASE_TYPE}"
    echo "Admin User:         ${ADMIN_USERNAME}"
    echo "AdGuard Home:       ${ADGUARD_ENABLED}"
    echo "Fail2Ban:           ${FAIL2BAN_ENABLED}"
    echo "XanMod Kernel:      ${INSTALL_XANMOD}"
    echo ""
    echo "=============================================="
    echo ""
    
    if ! ask_yes_no "Proceed with installation?" "y"; then
        log_info "Installation cancelled by user"
        exit 0
    fi
}

#-------------------------------------------------------------------------------
# Load Configuration (for non-interactive/resume mode)
#-------------------------------------------------------------------------------
load_configuration() {
    if [[ -f "${CONFIG_FILE}" ]]; then
        # shellcheck source=/dev/null
        source "${CONFIG_FILE}"
        return 0
    fi
    return 1
}

#-------------------------------------------------------------------------------
# Installation Phases
#-------------------------------------------------------------------------------
phase_pre_checks() {
    set_phase "Pre-flight Checks"
    log_info "Running pre-flight checks..."
    
    check_root
    check_os
    check_architecture
    check_resources 2 2048  # 2 CPU, 2GB RAM minimum
    
    log_success "All pre-flight checks passed"
}

phase_system_preparation() {
    set_phase "System Preparation"
    save_state "system_preparation"
    
    log_info "Preparing system..."
    
    # Update system
    system_update
    
    # Install essential packages
    install_essential_packages
    
    # Configure DNS (disable systemd-resolved stub)
    disable_systemd_resolved_stub
    
    # Set timezone
    if [[ -n "${ADMIN_EMAIL:-}" ]]; then
        configure_timezone
    fi
    
    log_success "System preparation complete"
}

phase_kernel_upgrade() {
    set_phase "Kernel Upgrade"
    
    if [[ "${INSTALL_XANMOD}" == "true" ]]; then
        save_state "kernel_upgrade" "started"
        
        if install_xanmod_kernel; then
            save_state "kernel_upgrade" "completed"
            log_success "XanMod kernel installed"
            
            # Check if reboot is needed
            if [[ "$(uname -r)" != *"xanmod"* ]]; then
                log_warn "Reboot required to activate new kernel"
                save_state "kernel_upgrade" "reboot_pending"
                
                if ask_yes_no "Reboot now? Installation will resume automatically." "y"; then
                    setup_resume_after_reboot
                    log_info "Rebooting in 5 seconds..."
                    sleep 5
                    reboot
                fi
            fi
        fi
    else
        # Just enable BBR on existing kernel
        enable_bbr
    fi
    
    log_success "Kernel/BBR configuration complete"
}

phase_docker() {
    set_phase "Docker Installation"
    save_state "docker"
    
    log_info "Installing Docker..."
    
    install_docker
    configure_docker_daemon
    verify_docker
    
    log_success "Docker installation complete"
}

phase_firewall() {
    set_phase "Firewall Configuration"
    save_state "firewall"
    
    log_info "Configuring firewall..."
    
    configure_ufw
    
    if [[ "${FAIL2BAN_ENABLED}" == "true" ]]; then
        setup_fail2ban
    fi
    
    log_success "Firewall configuration complete"
}

phase_nginx() {
    set_phase "Nginx Installation"
    save_state "nginx"
    
    log_info "Installing and configuring Nginx..."
    
    install_nginx
    configure_nginx_main
    configure_nginx_sni_routing "${PANEL_DOMAIN}" "${CDN_DOMAIN:-}" "${REALITY_DEST}"
    setup_fake_website
    generate_dhparams
    
    # Validate and reload
    if validate_nginx_config; then
        restart_nginx
    else
        log_error "Nginx configuration validation failed"
        return 1
    fi
    
    log_success "Nginx installation complete"
}

phase_ssl() {
    set_phase "SSL Certificate"
    save_state "ssl"
    
    # Skip if SSL is managed by CDN
    if [[ "${SSL_MANAGED_BY_CDN:-false}" == "true" ]]; then
        log_info "SSL managed by CDN, skipping certificate installation"
        return 0
    fi
    
    log_info "Obtaining SSL certificates..."
    
    install_certbot
    
    # Obtain certificate for panel domain
    if [[ -n "${PANEL_DOMAIN}" ]]; then
        obtain_certificate "${PANEL_DOMAIN}" "${ADMIN_EMAIL:-}"
    fi
    
    # Obtain certificate for CDN domain if enabled
    if [[ "${PROFILE_WHITELIST_ENABLED}" == "true" ]] && [[ -n "${CDN_DOMAIN:-}" ]]; then
        obtain_certificate "${CDN_DOMAIN}" "${ADMIN_EMAIL:-}"
    fi
    
    # Setup auto-renewal
    setup_certbot_auto_renewal
    
    log_success "SSL certificates installed"
}

phase_marzban() {
    set_phase "Marzban Installation"
    save_state "marzban"
    
    log_info "Installing Marzban..."
    
    # Setup directories
    setup_marzban_directories
    
    # Clone Marzban
    clone_marzban
    
    # Generate docker-compose.yml
    generate_marzban_compose
    
    # Generate .env file
    generate_marzban_env
    
    # Generate base Xray config
    setup_xray_base_config
    
    log_success "Marzban base installation complete"
}

phase_xray_keys() {
    set_phase "Xray Key Generation"
    save_state "xray_keys"
    
    log_info "Generating Xray keys..."
    
    # Ensure Reality keys exist
    ensure_reality_keys
    
    log_success "Xray keys generated"
}

phase_warp() {
    set_phase "WARP Configuration"
    
    if [[ "${PROFILE_WARP_ENABLED}" != "true" ]]; then
        log_info "WARP profile disabled, skipping"
        return 0
    fi
    
    save_state "warp"
    
    log_info "Setting up Cloudflare WARP..."
    
    setup_warp
    
    log_success "WARP configuration complete"
}

phase_adguard() {
    set_phase "AdGuard Home"
    
    if [[ "${ADGUARD_ENABLED}" != "true" ]]; then
        log_info "AdGuard Home disabled, skipping"
        return 0
    fi
    
    save_state "adguard"
    
    log_info "Setting up AdGuard Home..."
    
    setup_adguard_home
    
    log_success "AdGuard Home configuration complete"
}

phase_start_services() {
    set_phase "Starting Services"
    save_state "start_services"
    
    log_info "Starting all services..."
    
    # Start Marzban
    start_marzban
    
    # Wait for Marzban to be ready
    log_info "Waiting for Marzban to start..."
    sleep 10
    
    log_success "Services started"
}

phase_api_configuration() {
    set_phase "API Configuration"
    save_state "api_configuration"
    
    log_info "Configuring profiles via Marzban API..."
    
    # Wait for API to be ready
    if ! wait_for_api; then
        log_error "Marzban API not responding after timeout"
        return 1
    fi
    
    # Authenticate
    if ! api_authenticate "${ADMIN_USERNAME}" "${ADMIN_PASSWORD}"; then
        log_error "Failed to authenticate with Marzban API"
        return 1
    fi
    
    # Create profiles via API
    setup_profiles_via_api
    
    log_success "API configuration complete"
}

phase_finalize() {
    set_phase "Finalization"
    save_state "finalize"
    
    log_info "Finalizing installation..."
    
    # Save credentials
    save_credentials
    
    # Clear installation state
    clear_state
    
    # Run health check
    run_health_check
    
    log_success "Installation complete!"
}

#-------------------------------------------------------------------------------
# Resume After Reboot
#-------------------------------------------------------------------------------
setup_resume_after_reboot() {
    local service_file="/etc/systemd/system/marzban-installer-resume.service"
    
    cat > "${service_file}" << EOF
[Unit]
Description=Marzban Installer Resume
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=${SCRIPT_DIR}/install.sh --resume
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
EOF
    
    systemctl daemon-reload
    systemctl enable marzban-installer-resume.service
}

remove_resume_service() {
    local service_file="/etc/systemd/system/marzban-installer-resume.service"
    
    if [[ -f "${service_file}" ]]; then
        systemctl disable marzban-installer-resume.service 2>/dev/null || true
        rm -f "${service_file}"
        systemctl daemon-reload
    fi
}

#-------------------------------------------------------------------------------
# Save Credentials
#-------------------------------------------------------------------------------
save_credentials() {
    mkdir -p "$(dirname "${CREDENTIALS_FILE}")"
    
    cat > "${CREDENTIALS_FILE}" << EOF
# Marzban Credentials
# Generated: $(date -Iseconds)
# KEEP THIS FILE SECURE!

PANEL_URL=https://${PANEL_DOMAIN}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Database
DATABASE_TYPE=${DATABASE_TYPE}
EOF

    if [[ "${DATABASE_TYPE}" == "mariadb" ]]; then
        cat >> "${CREDENTIALS_FILE}" << EOF
MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-}
MARIADB_PASSWORD=${MARIADB_PASSWORD:-}
EOF
    fi

    if [[ "${ADGUARD_ENABLED}" == "true" ]]; then
        cat >> "${CREDENTIALS_FILE}" << EOF

# AdGuard Home
ADGUARD_URL=http://${PANEL_DOMAIN}:3000
ADGUARD_USERNAME=${ADMIN_USERNAME}
ADGUARD_PASSWORD=${ADMIN_PASSWORD}
EOF
    fi

    chmod 600 "${CREDENTIALS_FILE}"
}

#-------------------------------------------------------------------------------
# Health Check
#-------------------------------------------------------------------------------
run_health_check() {
    echo ""
    echo "=============================================="
    echo "         HEALTH CHECK"
    echo "=============================================="
    echo ""
    
    local checks_passed=0
    local checks_total=0
    
    # Check Docker
    ((checks_total++))
    if docker info &>/dev/null; then
        echo "✓ Docker: Running"
        ((checks_passed++))
    else
        echo "✗ Docker: Not running"
    fi
    
    # Check Marzban container
    ((checks_total++))
    if docker ps --format '{{.Names}}' | grep -q "marzban"; then
        echo "✓ Marzban: Running"
        ((checks_passed++))
    else
        echo "✗ Marzban: Not running"
    fi
    
    # Check Nginx
    ((checks_total++))
    if systemctl is-active --quiet nginx; then
        echo "✓ Nginx: Running"
        ((checks_passed++))
    else
        echo "✗ Nginx: Not running"
    fi
    
    # Check UFW
    ((checks_total++))
    if ufw status | grep -q "Status: active"; then
        echo "✓ Firewall: Active"
        ((checks_passed++))
    else
        echo "✗ Firewall: Inactive"
    fi
    
    # Check BBR
    ((checks_total++))
    if sysctl net.ipv4.tcp_congestion_control 2>/dev/null | grep -q "bbr"; then
        echo "✓ BBR: Enabled"
        ((checks_passed++))
    else
        echo "✗ BBR: Not enabled"
    fi
    
    # Check SSL
    if [[ "${SSL_MANAGED_BY_CDN:-false}" != "true" ]]; then
        ((checks_total++))
        if [[ -f "/etc/letsencrypt/live/${PANEL_DOMAIN}/fullchain.pem" ]]; then
            echo "✓ SSL Certificate: Valid"
            ((checks_passed++))
        else
            echo "✗ SSL Certificate: Not found"
        fi
    fi
    
    # Check AdGuard if enabled
    if [[ "${ADGUARD_ENABLED}" == "true" ]]; then
        ((checks_total++))
        if docker ps --format '{{.Names}}' | grep -q "adguard"; then
            echo "✓ AdGuard Home: Running"
            ((checks_passed++))
        else
            echo "✗ AdGuard Home: Not running"
        fi
    fi
    
    echo ""
    echo "Health Check: ${checks_passed}/${checks_total} passed"
    echo ""
}

#-------------------------------------------------------------------------------
# Show Final Summary
#-------------------------------------------------------------------------------
show_final_summary() {
    clear
    
    echo ""
    echo "╔══════════════════════════════════════════════════════════════════╗"
    echo "║                                                                  ║"
    echo "║     🎉 MARZBAN INSTALLATION COMPLETE! 🎉                         ║"
    echo "║                                                                  ║"
    echo "╚══════════════════════════════════════════════════════════════════╝"
    echo ""
    echo "═══════════════════════════════════════════════════════════════════"
    echo "                      ACCESS INFORMATION"
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    echo "  📌 Panel URL:      https://${PANEL_DOMAIN}"
    echo "  👤 Admin User:     ${ADMIN_USERNAME}"
    echo "  🔑 Admin Password: ${ADMIN_PASSWORD}"
    echo ""
    
    if [[ "${ADGUARD_ENABLED}" == "true" ]]; then
        echo "  📌 AdGuard URL:    http://${PANEL_DOMAIN}:3000"
        echo ""
    fi
    
    echo "═══════════════════════════════════════════════════════════════════"
    echo "                      ENABLED PROFILES"
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    
    if [[ "${PROFILE_STANDARD_ENABLED}" == "true" ]]; then
        echo "  ✓ Standard (VLESS+Reality) - Direct connection"
    fi
    
    if [[ "${PROFILE_WARP_ENABLED}" == "true" ]]; then
        echo "  ✓ WARP (via Cloudflare) - For geo-restricted services"
    fi
    
    if [[ "${PROFILE_WHITELIST_ENABLED}" == "true" ]]; then
        echo "  ✓ Whitelist Bypass (CDN-fronted) - For restrictive networks"
        echo "    CDN Domain: ${CDN_DOMAIN}"
        echo "    Provider: ${CDN_PROVIDER}"
    fi
    
    echo ""
    echo "═══════════════════════════════════════════════════════════════════"
    echo "                      IMPORTANT FILES"
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    echo "  📁 Credentials:    ${CREDENTIALS_FILE}"
    echo "  📁 Configuration:  ${CONFIG_FILE}"
    echo "  📁 Marzban Dir:    ${MARZBAN_DIR}"
    echo "  📁 Keys:           ${KEYS_DIR}"
    echo ""
    echo "═══════════════════════════════════════════════════════════════════"
    echo "                      USEFUL COMMANDS"
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    echo "  View logs:         marzban logs"
    echo "  Restart Marzban:   marzban restart"
    echo "  Check status:      marzban status"
    echo "  Backup config:     ${SCRIPT_DIR}/tools/backup.sh"
    echo ""
    
    if [[ "${PROFILE_WHITELIST_ENABLED}" == "true" ]]; then
        echo "═══════════════════════════════════════════════════════════════════"
        echo "                      CDN SETUP REQUIRED"
        echo "═══════════════════════════════════════════════════════════════════"
        echo ""
        echo "  To complete whitelist bypass setup, configure your CDN:"
        echo ""
        echo "  1. Add ${CDN_DOMAIN} to your CDN"
        echo "  2. Set origin to your server IP: $(get_public_ip)"
        echo "  3. Enable WebSocket support"
        echo "  4. Run: ${TOOLS_DIR}/clean-ip-scanner.sh"
        echo ""
    fi
    
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    echo "  Thank you for using Marzban Ultimate VPN Installer!"
    echo "  For support, visit: https://github.com/Gozargah/Marzban"
    echo ""
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
}

#-------------------------------------------------------------------------------
# Main Installation Flow
#-------------------------------------------------------------------------------
run_installation() {
    # Initialize logging
    mkdir -p "$(dirname "${LOG_FILE}")"
    exec > >(tee -a "${LOG_FILE}") 2>&1
    
    # Set error trap
    set_error_trap
    
    # Determine starting phase
    local start_phase="pre_checks"
    
    if [[ -f "${STATE_FILE}" ]]; then
        load_state
        case "${PHASE:-}" in
            "kernel_upgrade")
                if [[ "${STEP:-}" == "reboot_pending" ]]; then
                    # After reboot, remove resume service and continue
                    remove_resume_service
                    start_phase="docker"
                fi
                ;;
            "docker"|"firewall"|"nginx"|"ssl"|"marzban"|"xray_keys"|"warp"|"adguard"|"start_services"|"api_configuration"|"finalize")
                start_phase="${PHASE}"
                ;;
        esac
    fi
    
    # Load configuration
    if ! load_configuration; then
        log_error "Configuration not found. Run wizard first."
        exit 1
    fi
    
    # Execute phases
    local phases=(
        "pre_checks"
        "system_preparation"
        "kernel_upgrade"
        "docker"
        "firewall"
        "nginx"
        "ssl"
        "marzban"
        "xray_keys"
        "warp"
        "adguard"
        "start_services"
        "api_configuration"
        "finalize"
    )
    
    local started=false
    
    for phase in "${phases[@]}"; do
        if [[ "${started}" == "false" ]]; then
            if [[ "${phase}" == "${start_phase}" ]]; then
                started=true
            else
                continue
            fi
        fi
        
        case "${phase}" in
            "pre_checks") phase_pre_checks ;;
            "system_preparation") phase_system_preparation ;;
            "kernel_upgrade") phase_kernel_upgrade ;;
            "docker") phase_docker ;;
            "firewall") phase_firewall ;;
            "nginx") phase_nginx ;;
            "ssl") phase_ssl ;;
            "marzban") phase_marzban ;;
            "xray_keys") phase_xray_keys ;;
            "warp") phase_warp ;;
            "adguard") phase_adguard ;;
            "start_services") phase_start_services ;;
            "api_configuration") phase_api_configuration ;;
            "finalize") phase_finalize ;;
        esac
    done
    
    # Show final summary
    show_final_summary
}

#-------------------------------------------------------------------------------
# CLI Argument Parsing
#-------------------------------------------------------------------------------
show_help() {
    cat << EOF
${SCRIPT_NAME} v${SCRIPT_VERSION}

Usage: $(basename "$0") [OPTIONS]

Options:
    -h, --help          Show this help message
    -v, --version       Show version
    --resume            Resume interrupted installation
    --uninstall         Remove Marzban and all components
    --status            Show installation status
    --reconfigure       Re-run configuration wizard
    --update            Update Marzban to latest version

Examples:
    ./install.sh                    # Run interactive installation
    ./install.sh --resume           # Resume after reboot
    ./install.sh --status           # Check installation status
    ./install.sh --uninstall        # Remove everything

For more information, visit:
    https://github.com/Gozargah/Marzban

EOF
}

show_version() {
    echo "${SCRIPT_NAME} v${SCRIPT_VERSION}"
}

show_status() {
    echo ""
    echo "${SCRIPT_NAME} - Status"
    echo "========================="
    echo ""
    
    # Check installation state
    if [[ -f "${STATE_FILE}" ]]; then
        load_state
        echo "Installation State: In Progress"
        echo "Current Phase: ${PHASE:-unknown}"
        echo "Last Step: ${STEP:-unknown}"
        echo "Timestamp: ${TIMESTAMP:-unknown}"
    elif [[ -f "${CONFIG_FILE}" ]]; then
        echo "Installation State: Complete"
    else
        echo "Installation State: Not Started"
    fi
    
    echo ""
    
    # Run health check if installed
    if [[ -f "${CONFIG_FILE}" ]]; then
        load_configuration
        run_health_check
    fi
}

do_uninstall() {
    echo ""
    log_warn "This will remove Marzban and all related components!"
    echo ""
    
    if ! ask_yes_no "Are you sure you want to uninstall?" "n"; then
        log_info "Uninstall cancelled"
        exit 0
    fi
    
    if ! ask_yes_no "Do you want to backup data before uninstalling?" "y"; then
        log_info "Skipping backup"
    else
        # Run backup
        if [[ -x "${TOOLS_DIR}/backup.sh" ]]; then
            "${TOOLS_DIR}/backup.sh"
        fi
    fi
    
    log_info "Stopping services..."
    
    # Stop Marzban
    if [[ -f "${MARZBAN_DIR}/docker-compose.yml" ]]; then
        cd "${MARZBAN_DIR}" && docker compose down -v 2>/dev/null || true
    fi
    
    # Stop and disable services
    systemctl stop nginx 2>/dev/null || true
    systemctl disable nginx 2>/dev/null || true
    
    log_info "Removing files..."
    
    # Remove Marzban
    rm -rf "${MARZBAN_DIR}"
    rm -rf "${MARZBAN_DATA_DIR}"
    
    # Remove nginx configs
    rm -f /etc/nginx/sites-enabled/marzban*
    rm -f /etc/nginx/sites-available/marzban*
    rm -f /etc/nginx/stream.d/*.conf
    
    # Remove CLI
    rm -f /usr/local/bin/marzban
    
    # Remove resume service
    remove_resume_service
    
    # Remove installer data (optional)
    if ask_yes_no "Remove installer data and configuration?" "n"; then
        rm -rf "${DATA_DIR}"
    fi
    
    log_success "Uninstall complete"
}

#-------------------------------------------------------------------------------
# Main Entry Point
#-------------------------------------------------------------------------------
main() {
    # Parse arguments
    case "${1:-}" in
        -h|--help)
            show_help
            exit 0
            ;;
        -v|--version)
            show_version
            exit 0
            ;;
        --resume)
            load_modules
            run_installation
            exit 0
            ;;
        --status)
            load_modules
            show_status
            exit 0
            ;;
        --uninstall)
            load_modules
            do_uninstall
            exit 0
            ;;
        --reconfigure)
            load_modules
            clear_state
            rm -f "${CONFIG_FILE}"
            run_wizard
            run_installation
            exit 0
            ;;
        --update)
            load_modules
            log_info "Updating Marzban..."
            cd "${MARZBAN_DIR}" && docker compose pull && docker compose up -d
            log_success "Update complete"
            exit 0
            ;;
        "")
            # Default: interactive installation
            load_modules
            run_wizard
            run_installation
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
}

# Run main
main "$@"
