version: "3.8"

# =============================================================================
# Marzban Docker Compose Configuration
# Generated by Marzban Installer
# =============================================================================

services:
  marzban:
    image: gozargah/marzban:latest
    container_name: marzban
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./xray_config.json:/var/lib/marzban/xray_config.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${MARZBAN_DASHBOARD_PORT:-8001}/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - xray

  # Optional: Standalone Xray container (if not using Marzban's built-in Xray)
  # Uncomment if you need separate Xray management
  # xray:
  #   image: ghcr.io/xtls/xray-core:latest
  #   container_name: xray
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #     - ./xray_config.json:/etc/xray/config.json:ro
  #     - /var/lib/marzban/logs:/var/log/xray
  #   command: ["run", "-c", "/etc/xray/config.json"]

# =============================================================================
# Optional: MariaDB Database
# Uncomment this section to use MariaDB instead of SQLite
# =============================================================================
#   db:
#     image: mariadb:10.11
#     container_name: marzban-db
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-rootpassword}
#       MYSQL_DATABASE: marzban
#       MYSQL_USER: marzban
#       MYSQL_PASSWORD: ${MARIADB_PASSWORD:-password}
#     volumes:
#       - mariadb_data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#     networks:
#       - marzban-network

# =============================================================================
# Optional: Redis Cache
# Uncomment this section to enable Redis caching
# =============================================================================
#   redis:
#     image: redis:7-alpine
#     container_name: marzban-redis
#     restart: unless-stopped
#     command: redis-server --appendonly yes
#     volumes:
#       - redis_data:/data
#     networks:
#       - marzban-network

# =============================================================================
# Volumes
# =============================================================================
# volumes:
#   mariadb_data:
#   redis_data:

# =============================================================================
# Networks
# =============================================================================
# networks:
#   marzban-network:
#     driver: bridge
