# Marzban Ultimate VPN - Site Configuration
# Generated by installer - Do not edit manually

# HTTP redirect to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name ${PANEL_DOMAIN};
    
    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/html;
        allow all;
    }
    
    # Redirect all other traffic to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS server for Marzban panel (internal port for stream proxy)
server {
    listen ${MARZBAN_HTTPS_PORT} ssl http2;
    listen [::]:${MARZBAN_HTTPS_PORT} ssl http2;
    server_name ${PANEL_DOMAIN};
    
    # SSL Configuration
    ssl_certificate ${SSL_CERT_PATH};
    ssl_certificate_key ${SSL_KEY_PATH};
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    
    # Root for static files
    root /var/www/html;
    index index.html;
    
    # Dashboard location
    location ${DASHBOARD_PATH} {
        proxy_pass http://127.0.0.1:${MARZBAN_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # Buffering
        proxy_buffering off;
        proxy_buffer_size 4k;
    }
    
    # API location
    location /api {
        proxy_pass http://127.0.0.1:${MARZBAN_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Disable buffering for API
        proxy_buffering off;
    }
    
    # Subscription location
    location /sub {
        proxy_pass http://127.0.0.1:${MARZBAN_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Static files with caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri @proxy;
    }
    
    # Fallback to proxy
    location @proxy {
        proxy_pass http://127.0.0.1:${MARZBAN_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Root serves fake website or redirects to dashboard
    location = / {
        # Option 1: Serve fake website
        try_files $uri $uri/ /index.html;
        
        # Option 2: Redirect to dashboard (uncomment if preferred)
        # return 302 ${DASHBOARD_PATH};
    }
    
    # Health check endpoint
    location /health {
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }
    
    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
    
    # Logging
    access_log /var/log/nginx/${PANEL_DOMAIN}.access.log detailed;
    error_log /var/log/nginx/${PANEL_DOMAIN}.error.log warn;
}

# Fake website server (camouflage)
server {
    listen 8080;
    listen [::]:8080;
    server_name _;
    
    root /var/www/html;
    index index.html index.htm;
    
    # Serve static files
    location / {
        try_files $uri $uri/ =404;
    }
    
    # Basic security
    location ~ /\. {
        deny all;
    }
    
    # Minimal logging
    access_log /var/log/nginx/fake_site.access.log;
    error_log /var/log/nginx/fake_site.error.log warn;
}
