# Marzban Ultimate VPN - Stream Configuration (SNI Routing)
# Generated by installer - Do not edit manually
#
# Traffic Flow:
# Port 443 -> SNI Inspection -> Route to appropriate backend
#   - Reality SNI -> Xray (port ${XRAY_PORT})
#   - Panel domain -> Marzban HTTPS (port ${MARZBAN_HTTPS_PORT})
#   - Other/Invalid -> Fake website (port 8080)

# Map SNI to upstream backend
map $ssl_preread_server_name $backend_name {
    # Route Reality connections to Xray
    # These domains are used for Reality protocol camouflage
    ${REALITY_SERVER_NAMES_MAP}
    
    # Route panel domain to Marzban (HTTPS termination)
    ${PANEL_DOMAIN}    marzban_https;
    
    # Default: route to fake website
    default            fake_site;
}

# Upstream: Xray Reality backend (Profile 1)
upstream xray_reality_1 {
    server 127.0.0.1:${XRAY_REALITY_PORT_1};
}

# Upstream: Xray Reality backend (Profile 2)
upstream xray_reality_2 {
    server 127.0.0.1:${XRAY_REALITY_PORT_2};
}

# Upstream: Xray Reality backend (Profile 3 - WARP)
upstream xray_reality_3 {
    server 127.0.0.1:${XRAY_REALITY_PORT_3};
}

# Upstream: Marzban HTTPS backend (with SSL termination by Nginx)
upstream marzban_https {
    server 127.0.0.1:${MARZBAN_HTTPS_PORT};
}

# Upstream: Fake website backend
upstream fake_site {
    server 127.0.0.1:8080;
}

# Main listener on port 443
server {
    listen 443 reuseport;
    listen [::]:443 reuseport;
    
    # Enable SNI inspection without terminating SSL
    ssl_preread on;
    
    # Proxy settings
    proxy_pass $backend_name;
    proxy_protocol off;
    
    # Timeouts
    proxy_connect_timeout 10s;
    proxy_timeout 300s;
    
    # Buffer sizes
    proxy_buffer_size 16k;
}

# Alternative: Direct Xray listeners (optional, for non-SNI routing)
# Uncomment if you want dedicated ports for each Reality profile
# server {
#     listen ${XRAY_ALT_PORT_1};
#     listen [::]:${XRAY_ALT_PORT_1};
#     proxy_pass xray_reality_1;
#     proxy_protocol off;
# }
