#!/bin/bash
#===============================================================================
#
#          FILE: subscription-generator.sh
#
#         USAGE: ./subscription-generator.sh [OPTIONS]
#
#   DESCRIPTION: Generate client subscription links and QR codes for Marzban
#
#        AUTHOR: Generated by Claude (Anthropic)
#       VERSION: 1.0.0
#
#===============================================================================

set -euo pipefail

#-------------------------------------------------------------------------------
# Configuration
#-------------------------------------------------------------------------------
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DATA_DIR="${SCRIPT_DIR}/../data"
readonly CONFIG_FILE="${DATA_DIR}/config.env"
readonly KEYS_DIR="${DATA_DIR}/keys"
readonly OUTPUT_DIR="${DATA_DIR}/subscriptions"

#-------------------------------------------------------------------------------
# Logging
#-------------------------------------------------------------------------------
log_info() { echo -e "\033[0;34m[INFO]\033[0m $*"; }
log_success() { echo -e "\033[0;32m[OK]\033[0m $*"; }
log_warn() { echo -e "\033[0;33m[WARN]\033[0m $*"; }
log_error() { echo -e "\033[0;31m[ERROR]\033[0m $*" >&2; }

#-------------------------------------------------------------------------------
# Help
#-------------------------------------------------------------------------------
show_help() {
    cat << EOF
Subscription Generator v1.0.0

Generate VLESS subscription links and configs for clients.

Usage: $(basename "$0") [OPTIONS]

Options:
    -u, --user USERNAME     Username for subscription
    -p, --profile PROFILE   Profile type: standard, warp, whitelist (default: all)
    -f, --format FORMAT     Output format: link, json, qr, all (default: link)
    -o, --output DIR        Output directory
    --clean-ip IP           Use specific clean IP for CDN profile
    -h, --help              Show this help message

Examples:
    $(basename "$0") -u john                        # Generate all links for user john
    $(basename "$0") -u john -p standard -f qr     # Generate QR for standard profile
    $(basename "$0") -u john --clean-ip 1.2.3.4   # Use specific clean IP

EOF
}

#-------------------------------------------------------------------------------
# Load Configuration
#-------------------------------------------------------------------------------
load_config() {
    if [[ -f "${CONFIG_FILE}" ]]; then
        # shellcheck source=/dev/null
        source "${CONFIG_FILE}"
    else
        log_error "Configuration not found: ${CONFIG_FILE}"
        exit 1
    fi
    
    # Load keys
    if [[ -f "${KEYS_DIR}/reality_keys.json" ]]; then
        REALITY_PUBLIC_KEY=$(jq -r '.public_key' "${KEYS_DIR}/reality_keys.json")
        REALITY_SHORT_IDS=$(jq -r '.short_ids[0]' "${KEYS_DIR}/reality_keys.json")
    fi
}

#-------------------------------------------------------------------------------
# Generate UUID for user
#-------------------------------------------------------------------------------
generate_user_uuid() {
    local username="$1"
    
    # Use deterministic UUID based on username for consistency
    echo -n "${username}" | md5sum | sed 's/^\(.\{8\}\)\(.\{4\}\)\(.\{4\}\)\(.\{4\}\)\(.\{12\}\).*/\1-\2-\3-\4-\5/'
}

#-------------------------------------------------------------------------------
# Generate VLESS Link
#-------------------------------------------------------------------------------
generate_vless_link() {
    local uuid="$1"
    local address="$2"
    local port="$3"
    local name="$4"
    local security="$5"
    local params="$6"
    
    local encoded_name
    encoded_name=$(echo -n "${name}" | jq -sRr @uri)
    
    echo "vless://${uuid}@${address}:${port}?${params}#${encoded_name}"
}

#-------------------------------------------------------------------------------
# Generate Standard Profile Link
#-------------------------------------------------------------------------------
generate_standard_link() {
    local username="$1"
    local uuid="$2"
    
    local address="${PANEL_DOMAIN}"
    local port="${REALITY_PORT:-443}"
    local sni="${REALITY_DEST:-www.microsoft.com}"
    local fp="chrome"
    local pbk="${REALITY_PUBLIC_KEY:-}"
    local sid="${REALITY_SHORT_IDS:-}"
    
    local params="type=tcp&security=reality&sni=${sni}&fp=${fp}&pbk=${pbk}&sid=${sid}&flow=xtls-rprx-vision"
    
    generate_vless_link "${uuid}" "${address}" "${port}" "${username}-standard" "reality" "${params}"
}

#-------------------------------------------------------------------------------
# Generate WARP Profile Link
#-------------------------------------------------------------------------------
generate_warp_link() {
    local username="$1"
    local uuid="$2"
    
    local address="${PANEL_DOMAIN}"
    local port="${REALITY_PORT:-443}"
    local sni="${REALITY_DEST:-www.microsoft.com}"
    local fp="chrome"
    local pbk="${REALITY_PUBLIC_KEY:-}"
    local sid="${REALITY_SHORT_IDS:-}"
    
    # WARP uses same connection params but different server-side routing
    local params="type=tcp&security=reality&sni=${sni}&fp=${fp}&pbk=${pbk}&sid=${sid}&flow=xtls-rprx-vision"
    
    generate_vless_link "${uuid}" "${address}" "${port}" "${username}-warp" "reality" "${params}"
}

#-------------------------------------------------------------------------------
# Generate Whitelist (CDN) Profile Link
#-------------------------------------------------------------------------------
generate_whitelist_link() {
    local username="$1"
    local uuid="$2"
    local clean_ip="${3:-}"
    
    local address="${clean_ip:-${CDN_DOMAIN}}"
    local port="443"
    local host="${CDN_DOMAIN}"
    local path="${WS_PATH:-/ws}"
    
    # WebSocket + TLS through CDN
    local params="type=ws&security=tls&sni=${host}&host=${host}&path=${path}"
    
    generate_vless_link "${uuid}" "${address}" "${port}" "${username}-whitelist" "tls" "${params}"
}

#-------------------------------------------------------------------------------
# Generate QR Code
#-------------------------------------------------------------------------------
generate_qr() {
    local data="$1"
    local output_file="$2"
    
    if command -v qrencode &>/dev/null; then
        qrencode -t PNG -o "${output_file}" "${data}"
        return 0
    else
        # Try using online API (for display only)
        log_warn "qrencode not installed. Install with: apt install qrencode"
        
        # Generate ASCII QR
        if command -v qrencode &>/dev/null; then
            qrencode -t ANSI "${data}"
        fi
        return 1
    fi
}

#-------------------------------------------------------------------------------
# Generate All Formats
#-------------------------------------------------------------------------------
generate_all_formats() {
    local username="$1"
    local uuid="$2"
    local profile="$3"
    local link="$4"
    local output_dir="$5"
    
    mkdir -p "${output_dir}"
    
    # Save link
    echo "${link}" > "${output_dir}/${username}_${profile}.txt"
    
    # Generate JSON config
    cat > "${output_dir}/${username}_${profile}.json" << EOF
{
    "username": "${username}",
    "profile": "${profile}",
    "uuid": "${uuid}",
    "link": "${link}",
    "generated_at": "$(date -Iseconds)"
}
EOF
    
    # Generate QR
    if command -v qrencode &>/dev/null; then
        qrencode -t PNG -o "${output_dir}/${username}_${profile}.png" "${link}"
        log_success "QR code: ${output_dir}/${username}_${profile}.png"
    fi
}

#-------------------------------------------------------------------------------
# Display Links
#-------------------------------------------------------------------------------
display_link() {
    local profile="$1"
    local link="$2"
    
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  Profile: ${profile}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "${link}"
    echo ""
    
    # Display QR in terminal if possible
    if command -v qrencode &>/dev/null; then
        qrencode -t ANSI256 -m 1 "${link}" 2>/dev/null || true
    fi
}

#-------------------------------------------------------------------------------
# Main
#-------------------------------------------------------------------------------
main() {
    local username=""
    local profile="all"
    local format="link"
    local output_dir="${OUTPUT_DIR}"
    local clean_ip=""
    
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -u|--user)
                username="$2"
                shift 2
                ;;
            -p|--profile)
                profile="$2"
                shift 2
                ;;
            -f|--format)
                format="$2"
                shift 2
                ;;
            -o|--output)
                output_dir="$2"
                shift 2
                ;;
            --clean-ip)
                clean_ip="$2"
                shift 2
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done
    
    # Validate username
    if [[ -z "${username}" ]]; then
        read -rp "Enter username: " username
        if [[ -z "${username}" ]]; then
            log_error "Username is required"
            exit 1
        fi
    fi
    
    # Load configuration
    load_config
    
    # Generate UUID for user
    local uuid
    uuid=$(generate_user_uuid "${username}")
    
    log_info "Generating subscriptions for user: ${username}"
    log_info "UUID: ${uuid}"
    
    # Generate links
    local links=()
    
    if [[ "${profile}" == "all" ]] || [[ "${profile}" == "standard" ]]; then
        if [[ "${PROFILE_STANDARD_ENABLED:-true}" == "true" ]]; then
            local standard_link
            standard_link=$(generate_standard_link "${username}" "${uuid}")
            links+=("standard:${standard_link}")
            
            if [[ "${format}" == "link" ]] || [[ "${format}" == "all" ]]; then
                display_link "Standard (VLESS+Reality)" "${standard_link}"
            fi
        fi
    fi
    
    if [[ "${profile}" == "all" ]] || [[ "${profile}" == "warp" ]]; then
        if [[ "${PROFILE_WARP_ENABLED:-false}" == "true" ]]; then
            local warp_link
            warp_link=$(generate_warp_link "${username}" "${uuid}")
            links+=("warp:${warp_link}")
            
            if [[ "${format}" == "link" ]] || [[ "${format}" == "all" ]]; then
                display_link "WARP (via Cloudflare)" "${warp_link}"
            fi
        fi
    fi
    
    if [[ "${profile}" == "all" ]] || [[ "${profile}" == "whitelist" ]]; then
        if [[ "${PROFILE_WHITELIST_ENABLED:-false}" == "true" ]]; then
            local whitelist_link
            whitelist_link=$(generate_whitelist_link "${username}" "${uuid}" "${clean_ip}")
            links+=("whitelist:${whitelist_link}")
            
            if [[ "${format}" == "link" ]] || [[ "${format}" == "all" ]]; then
                display_link "Whitelist Bypass (CDN)" "${whitelist_link}"
            fi
        fi
    fi
    
    # Generate files if requested
    if [[ "${format}" == "json" ]] || [[ "${format}" == "qr" ]] || [[ "${format}" == "all" ]]; then
        mkdir -p "${output_dir}/${username}"
        
        for entry in "${links[@]}"; do
            IFS=':' read -r profile_name link <<< "${entry}"
            generate_all_formats "${username}" "${uuid}" "${profile_name}" "${link}" "${output_dir}/${username}"
        done
        
        log_success "Files saved to: ${output_dir}/${username}/"
    fi
    
    # Summary
    echo ""
    echo "═══════════════════════════════════════════════════════════════════"
    echo "  Generated ${#links[@]} subscription(s) for ${username}"
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    
    if [[ "${PROFILE_WHITELIST_ENABLED:-false}" == "true" ]] && [[ -z "${clean_ip}" ]]; then
        log_info "Tip: Run clean-ip-scanner.sh to find optimal CDN IPs"
        log_info "Then use: $(basename "$0") -u ${username} --clean-ip <IP>"
    fi
}

main "$@"
